engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - src/app/core/**
  - src/app/pages/**
exclude_paths:
- src/**/*.spec.js