engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript:
ratings:
  paths:
  - "**/*.js"
exclude_paths:
- "**/*.spec.js"
- "src/app/translations/"
- "src/generators/world-map/"