engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
        mass_threshold: 100
ratings:
  paths:
  - "**/*.js"
exclude_paths:
- "**/*.spec.js"
- "src/app/translations/"
- "src/generators/world-map/"